name: Test & Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    name: Run tests & deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: corepack enable

    - name: Install dependencies
      run: yarn install --immutable

    - name: Run unit tests
      run: yarn test

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ap-southeast-2

    - name: Deploy lambda
      run: yarn deploy:lambda
      env:
        AWS_EC2_METADATA_DISABLED: true

    - name: Deploy app
      run: yarn deploy:app
      env:
        AWS_EC2_METADATA_DISABLED: true

    - name: Deploy Terraform IAC
      run: |
        cd infra
        terraform init
        terraform apply -auto-approve
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        AWS_EC2_METADATA_DISABLED: true

    - name: Lint code
      run: |
        yarn lint
        terraform fmt -check
