name: Test & Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    name: Run tests & deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: corepack enable

    - name: Install dependencies
      run: yarn install --immutable

    - name: Initialise database for testing
      run: yarn initdb
      env:
        NODE_ENV: test

    - name: Run unit tests
      run: yarn test

    - name: Deploy lambda
      run: yarn deploy:lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_EC2_METADATA_DISABLED: true

    - name: Deploy app
      run: yarn deploy:app
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_EC2_METADATA_DISABLED: true

    - name: Deploy Terraform IAC
      run: |
        cd infra
        terraform init
        terraform apply -auto-approve
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_ccb_username: ${{ secrets.CCB_USERNAME }}
        TF_VAR_ccb_password: ${{ secrets.CCB_PASSWORD }}
        TF_VAR_bgf_password_hash: ${{ secrets.BGF_PASSWORD_HASH }}
        TF_VAR_bgf_password_salt: ${{ secrets.BGF_PASSWORD_SALT }}
        AWS_EC2_METADATA_DISABLED: true

    - name: Lint code
      run: |
        yarn lint
        terraform fmt -check
